"""Sub-agent spawning with the Subagent Result Contract (RFC v1.0.1).

The sub-agent is instructed to emit a structured Subagent Result Contract JSON
object. The orchestrator (this tool):
  * injects meta.task_id / subagent_instance_id (RFC: UUID injected by the
    orchestrator, not generated by the sub-agent),
  * validates the emitted JSON against the frozen contract (hard-fail on
    violations — no silent normalization, ADR-001),
  * routes error.category onto the Phase 3 correction strategies,
  * deduplicates results by (task_id, instance_id).

Sub-agents that don't emit contract JSON still work — the result falls back
to the original text path (backward compatible).
"""

import json
import time
import uuid

from ..contracts import (
    SUBAGENT_CONTRACT_PROMPT,
    SubagentResultValidator,
    category_to_strategy,
    new_instance_id,
    parse_result,
)
from .base import Tool

MAX_OUTPUT = 5000


class AgentTool(Tool):
    name = "agent"
    description = (
        "Spawn a sub-agent to handle a complex sub-task independently. "
        "The sub-agent has its own context and tool access and reports back "
        "with a structured result (status, confidence, error category, "
        "artifacts). Use this for: researching a codebase, implementing a "
        "multi-step change in isolation, or any task that would benefit from "
        "a fresh context window."
    )
    parameters = {
        "type": "object",
        "properties": {
            "task": {
                "type": "string",
                "description": "What the sub-agent should accomplish",
            },
        },
        "required": ["task"],
    }

    # set by Agent.__init__ after construction
    _parent_agent = None

    # (task_id, instance_id) -> validated result (v1.0.1 idempotent dedup)
    _result_cache: dict[tuple[str, str], dict] = {}
    _validator = SubagentResultValidator()

    def execute(self, task: str) -> str:
        if self._parent_agent is None:
            return "Error: agent tool not initialized (no parent agent)"

        # import here to avoid circular dep
        from ..agent import Agent

        parent = self._parent_agent
        sub = Agent(
            llm=parent.llm,
            tools=[t for t in parent.tools if t.name != "agent"],  # no recursive agents
            max_context_tokens=parent.context.max_tokens,
            max_rounds=20,
        )

        task_id = str(uuid.uuid4())
        instance_id = new_instance_id()
        started_wall = time.time()      # wall clock for ISO timestamps
        started_mono = time.monotonic()  # monotonic for duration_ms

        # contract-aware task: the sub-agent must echo the injected ids and
        # emit a contract JSON object as its final output
        prompt = (
            f"meta.task_id: {task_id}\nmeta.subagent_instance_id: {instance_id}\n"
            f"meta.subagent_name: {self.name}\n\n"
            f"{SUBAGENT_CONTRACT_PROMPT}\n\nTask: {task}"
        )

        try:
            raw = sub.chat(prompt)
        except Exception as e:
            return f"Sub-agent error: {e}"
        return self._finalize(task_id, instance_id, raw, started_wall, started_mono)

    # ------------------------------------------------------------ orchestrator

    def _finalize(self, task_id: str, instance_id: str, raw: str, started_wall: float, started_mono: float) -> str:
        cache_key = (task_id, instance_id)
        if cache_key in self._result_cache:
            cached = self._result_cache[cache_key]
            return (
                f"[Sub-agent result (cached, idempotent)]\n"
                f"[Sub-agent {cached.get('status')}] {cached.get('summary', '')}"
            )

        try:
            parsed = parse_result(raw)
        except json.JSONDecodeError:
            # not contract JSON -> backward-compatible text path
            trimmed = raw if len(raw) <= MAX_OUTPUT else raw[:4500] + "\n... (sub-agent output truncated)"
            return f"[Sub-agent completed]\n{trimmed}"

        # the orchestrator owns these ids; inject them regardless of what the
        # sub-agent echoed (RFC: "UUID 由 Orchestrator 注入")
        finished_mono = time.monotonic()
        meta = parsed.setdefault("meta", {})
        meta["task_id"] = task_id
        meta["subagent_instance_id"] = instance_id
        meta["started_at"] = _iso(started_wall)
        meta["finished_at"] = _iso(time.time())
        meta["duration_ms"] = int((finished_mono - started_mono) * 1000)

        errors = self._validator.validate(parsed)
        if errors:
            # ADR-001: hard-fail, no silent normalization -> permanent, never retry
            return (
                f"[Sub-agent contract violation (permanent)]\n"
                f"{'; '.join(errors)}\n"
                f"Raw output (truncated):\n{raw[:2000]}"
            )

        self._result_cache[cache_key] = parsed
        return self._format_contract(parsed)

    @staticmethod
    def _format_contract(result: dict) -> str:
        status = result.get("status", "?")
        conf = result.get("confidence", "")
        lines = [f"[Sub-agent {status} ({conf})] {result.get('summary', '')}"]
        if status == "partial":
            lines.append(f"completeness: {result.get('completeness_ratio')}")
        err = result.get("error")
        if err:
            strategy = category_to_strategy(err.get("category", ""))
            lines.append(
                f"error[{err.get('category')} -> {strategy}]: "
                f"{err.get('code')} — {err.get('message')}"
            )
        artifacts = result.get("artifacts") or []
        if artifacts:
            shown = ", ".join(f"{a.get('action')}:{a.get('path')}" for a in artifacts[:5])
            more = f" ... and {len(artifacts) - 5} more" if len(artifacts) > 5 else ""
            lines.append(f"artifacts ({len(artifacts)}): {shown}{more}")
        next_step = result.get("suggested_next_step")
        if next_step:
            lines.append(f"next: {next_step.get('type')}")
        return "\n".join(lines)


def _iso(epoch_seconds: float) -> str:
    import datetime

    return datetime.datetime.fromtimestamp(epoch_seconds, tz=datetime.timezone.utc).isoformat()
